### ISSUE TITLE
Undefined legal_drawtype

### ISSUE THREAD

**Issue by Montandalar** [rollerozxa/upscaled_gtex#1]
I saw this on ContentDB and thought I would look at the source. Immediately I saw `legal_drawtype` with no definition and no dependencies in `mod.conf` so that sent alarm bells ringing. And yeah it gives a stack trace immediately when in-game. You should probably include that function.

```
ModError: Runtime error from mod 'upscaled_gtex' in callback on_mods_loaded(): /home/[redacted]/.minetest/mods/upscaled_gtex/init.lua:9: attempt to call global 'legal_drawtype' (a nil value)
stack traceback:
	/home/[redacted]/.minetest/mods/upscaled_gtex/init.lua:9: in function </home/[redacted]/.minetest/mods/upscaled_gtex/init.lua:4>
	/usr/local/share/minetest/builtin/game/register.lua:446: in function </usr/local/share/minetest/builtin/game/register.lua:432>
Check debug.txt for details.
```

**Comment by rollerozxa** [comment]
Well that's great my mod was completely broken for two days without anyone noticing, haha.

`legal_drawtype` is supposed to check for the drawtype of each node, and disable scaling for drawtypes where it doesn't make sense or where it breaks things (e.g. raillike...), but I haven't gotten around to testing all of them. So I've removed the check for now for the version on here.
